### ISSUE TITLE
Android APK?

### ISSUE THREAD

**Issue by mossyhub** [twnlink/neptune-plugins#18]
Any ideas if its possible or what it might take to mod the Android APK to support Neptune, specifically the Remote Control you recently added?

**Comment by twnlink** [comment]
The remote desktop functionality is built by TIDAL themselves and *should* work with Android. If it doesn't work on Android, TIDAL has either broken it, or the functionality has had a bug. Their remote desktop implementation currently has numerous bugs which makes sense because it is not meant to be used. I have tried to fix what I can, but it still remains shoddy.
